[package]
name = "sdb_run_monitoring"
version = "0.1.0"
authors = ["Tarun Jaiswal <tarun.j@surya-soft.com>"]
edition = "2018"

[dependencies]
dotenv = "0.10"
diesel = { version = "1.3.3", features = ["sqlite"] }